### ISSUE TITLE
Question: running on CPU?

### ISSUE THREAD

**Issue by jmiller656** [Puzer/stylegan#14]
Do you know if it's possible to run stylegan on a GPU machine? Been trying to run a version of stylegan I've trained on my desktop machine and would like to mess around with the checkpoints while it's training. Keep seeing that the operations are specifically set to use GPU still.

Specifically, this error: 
```InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'Gs/_Run/Gs/latents_in': Operation was explicitly assigned to /device
:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
         [[Node: Gs/_Run/Gs/latents_in = Identity[T=DT_FLOAT, _device="/device:GPU:0"](Gs/_Run/split)]]```

**Comment by pbaylies** [comment]
@jmiller656 the original StyleGAN code is designed to be run with at least one GPU; if you just want to play around, I'd suggest using Google Colab, where you can load up a free notebook in the cloud and use one of their GPUs. Otherwise, you'd need to write or find an implementation that doesn't require a GPU.

**Comment by jmiller656** [comment]
Hmm, was trying to not have to drag my model onto google drive and deal with all that... guess I have no choice. Thanks!
